server:
  port: 8002

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: front-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_graduate?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.study.front.entities    # 所有Entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/files/

